# Generated by Django 3.2.1 on 2021-06-04 11:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('location', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200, null=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('description', models.CharField(max_length=200, null=True)),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('fpassword', models.CharField(max_length=200, null=True)),
                ('instagram', models.CharField(max_length=200, null=True)),
                ('ig_password', models.CharField(max_length=200, null=True)),
                ('tweeter', models.CharField(max_length=200, null=True)),
                ('tw_password', models.CharField(max_length=200, null=True)),
                ('wechat', models.CharField(max_length=200, null=True)),
                ('we_password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
