# Generated by Django 3.2.1 on 2021-06-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wconnects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mamage',
            new_name='Manage',
        ),
    ]
