# Generated by Django 3.2.1 on 2021-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wconnects', '0002_rename_mamage_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='facebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=200, null=True)),
                ('fpassword', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fpassword',
        ),
    ]
