# Generated by Django 3.2.1 on 2021-06-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wconnects', '0003_auto_20210604_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=200, null=True)),
                ('ig_password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(max_length=200, null=True)),
                ('tw_password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat', models.CharField(max_length=200, null=True)),
                ('we_password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='ig_password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='member',
            name='tw_password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='tweeter',
        ),
        migrations.RemoveField(
            model_name='member',
            name='we_password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='wechat',
        ),
    ]
