# Generated by Django 3.2.1 on 2021-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wconnects', '0004_auto_20210606_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='dislike',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='manage',
            name='followers',
            field=models.CharField(default='5k', max_length=200),
        ),
        migrations.AddField(
            model_name='manage',
            name='like',
            field=models.CharField(default='1k', max_length=200),
        ),
        migrations.AddField(
            model_name='manage',
            name='love',
            field=models.CharField(default='2.5k', max_length=200),
        ),
    ]
