# Generated by Django 3.2.1 on 2021-06-08 10:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wconnects', '0005_auto_20210608_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('location', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('like', models.CharField(default='1k', max_length=200)),
                ('dislike', models.CharField(default='0', max_length=200)),
                ('love', models.CharField(default='2.5k', max_length=200)),
                ('followers', models.CharField(default='5k', max_length=200)),
            ],
        ),
    ]
